version: '3.5'

services:
  mobile:
    container_name: owl-of-minerva
    privileged: true
    build:
      context: .
      args:
        BUILD_ENV: "development"
    command: bash -c "export PATH=$ANDROID_SDK/platform-tools:$PATH && npm install && npm start"
    env_file:
      - .env
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 9230:9229
    volumes:
      - .:/usr/local/src/owl-of-minerva
      - mobile_modules:/usr/local/src/owl-of-minerva/node_modules # do not link node_modules in, and persist it between dc up runs
volumes:
  mobile_modules: